Refactor/add-booking-screen-with-backend
Board-of-Directors/budle-mobile pull request #10
Opened 2023-03-24 05:43 UTC by Fagorym

2023-03-24 16:24 UTC, Tretiakovv approved these changes

2023-03-24 16:24 UTC, Tretiakovv commented on app/src/main/java/fit/budle/components/atoms/BookingCardRefactored.kt
> +
Тут гуд, но я тут понял ошибку в логике. Окей, мы не можем отменить **отмененную уже** бронь, но как их удалить с экрана? Они будут удаляться со временем? Думаю, глупо. Тогда на вкладке отмененных броней нужно будет реализовать возможность выборочно удалять брони (одну / все / несколько).

2023-03-24 16:24 UTC, Tretiakovv commented on app/src/main/java/fit/budle/components/moleculas/BookingCardListBackendConnected.kt
> +fun BudleBookingCardListBackendConnected(
Предлагаю не вносить в названия функций-компонентов их отношение к беку / фронту :) Они же так или иначе все backend-connected, разве нет?) Типа просто BudleBookingCardList.

2023-03-25 03:28 UTC, NikFive requested changes

2023-03-25 03:28 UTC, NikFive commented on app/src/main/java/fit/budle/components/atoms/BookingCardRefactored.kt
> +                painter = booking.establishmentImage.image!!,
!! нельзя юзать, всё приложение свалится, если вдруг не будет картинки

2023-03-25 03:28 UTC, NikFive commented on app/src/main/java/fit/budle/viewmodel/MainViewModel.kt
> +            when (val response = repository.getOrdersRequest(1)) {
1👍

2023-03-25 03:28 UTC, NikFive commented on app/src/main/java/fit/budle/viewmodel/MainViewModel.kt
> +            when (val response = repository.getOrdersRequest(1)) {
Хотя бы в переменную вынеси:)

2023-03-25 03:28 UTC, NikFive commented on app/src/main/java/fit/budle/repository/BudleRepository.kt
> +    suspend fun getOrdersRequest(userId: Long?): ResultList3 {
Чёт userId не используется вообще в этой функции

2023-03-25 03:28 UTC, NikFive commented on app/src/main/java/fit/budle/repository/BudleRepository.kt
> +            val result = budleAPIRequests.getOrders(1)
Видимо, userId должен быть тут:)

2023-03-25 03:56 UTC, Fagorym commented on app/src/main/java/fit/budle/components/moleculas/BookingCardListBackendConnected.kt
> +fun BudleBookingCardListBackendConnected(
Это для различия компонетов отрефакторенных (которые работают от бэка) и тех, которые работают от фронта. Пусть так лучше остается, чтоб не путаться сильно.

2023-03-25 06:34 UTC, merged